defmodule DocmapperPhxWeb.HardcodedValues do
  @moduledoc """
  Hard-coded values for dropdowns on main LiveView.
  """
  def genders do
    [
      %{label: "Any Gender", value: "any"},
      %{label: "a Man", value: "Male"},
      %{label: "a Woman", value: "Female"},
      %{label: "Non-Binary", value: "Non-Binary"}
    ]
  end

  # docs |> Enum.map(fn x -> x.specialty end) |> Enum.map(&String.split(&1, ", ")) |> List.flatten() |> Enum.uniq() |> Enum.sort() |> IO.inspect(limit: :infinity)

  def doc_types do
    [
      "a Family Physician",
      "Any Physician",
      "Addiction Medicine",
      "Adolescent Medicine",
      "Anatomical Pathology",
      "Anesthesiology",
      "Cardiac Surgery",
      "Cardiology",
      "Cardiothoracic Surgery",
      "Cardiovascular and Thoracic Surgery",
      "Child and Adolescent Psychiatry",
      "Clinical Immunology",
      "Clinical Immunology and Allergy",
      "Clinical Pharmacology",
      "Clinical Pharmacology and Toxicology",
      "Clinician Investigator Program",
      "Colorectal Surgery",
      "Community Medicine",
      "Critical Care Medicine",
      "Dermatology",
      "Developmental Pediatrics",
      "Diagnostic Radiology",
      "Diagnostic and Clinical Pathology",
      "Diagnostic and Molecular Pathology",
      "Emergency Medicine",
      "Endocrinology and Metabolism",
      "FCFP - Family Medicine",
      "Family Medicine",
      "Forensic Pathology",
      "Forensic Psychiatry",
      "Gastroenterology",
      "General Internal Medicine",
      "General Pathology",
      "General Surgery",
      "General Surgical Oncology",
      "Geriatric Medicine",
      "Geriatric Psychiatry",
      "Gynecologic Oncology",
      "Gynecologic Reproductive Endocrinology/Infertility",
      "Hematological Pathology",
      "Hematology",
      "Infectious Diseases",
      "Internal Medicine",
      "Interventional Radiology",
      "Laboratory Medicine",
      "Maternal Fetal Medicine",
      "Medical Biochemistry",
      "Medical Genetics and Genomics",
      "Medical Microbiology",
      "Medical Oncology",
      "Neonatal-Perinatal Medicine",
      "Nephrology",
      "Neurology",
      "Neuropathology",
      "Neuroradiology",
      "Neurosurgery",
      "No specialties reported",
      "Nuclear Medicine",
      "Obstetrics and Gynecology",
      "Occupational Medicine",
      "Ophthalmology",
      "Orthopedic Surgery",
      "Otolaryngology - Head and Neck Surgery",
      "Pain Medicine",
      "Palliative Medicine",
      "Pediatric Cardiology",
      "Pediatric Critical Care Medicine",
      "Pediatric Emergency Medicine",
      "Pediatric Endocrinology and Metabolism",
      "Pediatric Gastroenterology",
      "Pediatric General Surgery",
      "Pediatric Hematology/Oncology",
      "Pediatric Infectious Diseases",
      "Pediatric Nephrology",
      "Pediatric Neurology",
      "Pediatric Radiology",
      "Pediatric Respirology",
      "Pediatric Rheumatology",
      "Pediatric Surgery",
      "Pediatrics",
      "Physical Medicine and Rehabilitation",
      "Plastic Surgery",
      "Prehospital and Transport Medicine",
      "Psychiatry",
      "Public Health and Preventive Medicine",
      "Radiation Oncology",
      "Respirology",
      "Rheumatology",
      "Sport and Exercise Medicine",
      "Thoracic Surgery",
      "Urology",
      "Vascular Surgery"
    ]
  end

  # docs |> Enum.map(fn x -> x.languages_spoken end) |> Enum.map(&String.split(&1, ",")) |> List.flatten() |> Enum.uniq() |> Enum.map(&String.replace(&1, " ", "")) |> Enum.sort() |> IO.inspect(limit: :infinity)
  def languages do
    [
      "English",
      "French",
      "Acholi",
      "Afrikaans",
      "Akan",
      "Albanian",
      "American Sign Language",
      "Amharic",
      "Arabic",
      "Armenian",
      "Assyrian",
      "Azari",
      "Belarusian",
      "Bengali",
      "Bislama",
      "Bosnian",
      "Bulgarian",
      "Burmese",
      "Cambodian",
      "Cantonese",
      "Catalan",
      "Cebuano",
      "Chinese",
      "Creole",
      "Croatian",
      "Czech",
      "Danish",
      "Dari",
      "Dutch",
      "Eritrean",
      "Estonian",
      "Ethiopian",
      "Farsi",
      "Filipino",
      "Finnish",
      "Flemish",
      "Fukien",
      "Fuzhou",
      "Ga",
      "Ga-adangme-krobo",
      "Gaelic",
      "Ganda",
      "Georgian",
      "German",
      "Ghana",
      "Greek",
      "Gujarati",
      "Hakka",
      "Hausa",
      "Hebrew",
      "Hindi",
      "Hungarian",
      "Ibibio",
      "Ibo",
      "Icelandic",
      "Igbo",
      "Ilocano",
      "Indonesian",
      "Iranian",
      "Italian",
      "Jamaican Creole",
      "Japanese",
      "Kaamba",
      "Kabyle",
      "Kachchi",
      "Kannada",
      "Kashmiri",
      "Konkani",
      "Korean",
      "Kurdi",
      "Lao",
      "Latvian",
      "Lingala",
      "Lithuanian",
      "Macedonian",
      "Malay",
      "Malayalam",
      "Maltese",
      "Mandarin",
      "Marathi",
      "Mongolian",
      "Nepali",
      "Norwegian",
      "Nzema",
      "Ojibwa",
      "Oriya",
      "Other",
      "Panjabi/Punjabi",
      "Persian",
      "Polish",
      "Portuguese",
      "Pushto",
      "Romanian",
      "Russian",
      "Samoan",
      "Serbian",
      "Sesotho",
      "Sindhi",
      "Sinhala",
      "Sinhalese",
      "Slovak",
      "Slovenian",
      "Somalian",
      "Spanish",
      "Swahili",
      "Swatow",
      "Swedish",
      "Tagalog",
      "Taiwanese",
      "Tamil",
      "Telugu",
      "Thai",
      "Tigrigna",
      "Tiv",
      "Tulu",
      "Turkish",
      "Ukrainian",
      "Urdu",
      "Vietnamese",
      "Visayan",
      "Welsh",
      "Xhosa",
      "Yiddish",
      "Yoruba",
      "Yugoslav",
      "Zulu"
    ]
  end
end
